spring:
  application:
    name: sample-spring-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
server:
  port: 8090
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework: WARN
    com.example: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: when-authorized
      
  # Old deprecated properties (will be transformed)
  metrics:
    binders:
      jvm:
        enabled: true
      logback:
        enabled: true 